### ISSUE TITLE
Base Skyeye Image is pointed at Skyeye Scaler

### ISSUE THREAD

**Issue by Rabbit994** [dharmab/skyeye#307]
**Describe the bug**

Appears the Skyeye Docker Image is actually the scaler image

**Steps to Reproduce**

docker pull ghcr.io/dharmab/skyeye:latest;docker inspect ghcr.io/dharmab/skyeye:latest 

**Logs**

[
    {
        "Id": "sha256:cddd7b62c84a25dd02117491619c9612c4ded33a19785782e12e02d659538fde",
        "RepoTags": [
            "ghcr.io/dharmab/skyeye:latest"
        ],
        "RepoDigests": [
            "ghcr.io/dharmab/skyeye@sha256:8ad826e071fe6babb5c0f77f01c8b8069f137aee87a6f5d49fcfe4531742e10c"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2024-09-18T01:36:40.703780488Z",
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            **"Entrypoint": [
                "/opt/skyeye/bin/skyeye-scaler"
            ],**

You can also see it here: https://github.com/dharmab/skyeye/actions/runs/10913949817/job/30291295328#step:3:3139 Where it should be pushing main image.

**Platform Info**

Not Applicable

**Comment by dharmab** [comment]
Thanks for the report, this is fixed in v0.5.1
