### ISSUE TITLE
Picture proword missing from picture call

### ISSUE THREAD

**Issue by hbjonsson** [dharmab/skyeye#378]
Picture call should be prefaced by "Picture" ... blablabla" rather then just immediately starting with the groups.

i.e. should be "BOXCAR, PICTURE, 2 groups...."

2:27AM INF extended next PICTURE broadcast time callsign="viper 1 4" deadline=2024-11-08T02:37:20Z type=*brevity.PictureRequest
2:27AM INF composing brevity call params={"Count":2,"Groups":[{},{}]} type=brevity.PictureResponse
2:27AM INF composed brevity call params={"Count":2,"Groups":[{},{}]} speech="BOXCAR, 2 groups. Group bullseye 0 5 1, 64, 1000, track west, hostile, 2 contacts, Frogfoot. Group bullseye 0 4 4, 134, 31000, track south, hostile, Mainstay." subtitle="BOXCAR, 2 groups. Group bullseye 051/64, 1000, track west, hostile, 2 contacts, Frogfoot. Group bullseye 044/134, 31000, track south, hostile, Mainstay." type=brevity.PictureResponse
2:27AM INF synthesizing speech text="BOXCAR, 2 groups. Group bullseye 0 5 1, 64, 1000, track west, hostile, 2 contacts, Frogfoot. Group bullseye 0 4 4, 134, 31000, track south, hostile, Mainstay."
2:27AM INF synthesized audio clockTime=1.3430837s
2:27AM INF transmitting audio traceID=9KUVZGeTyAefmCeKwQHfDn

**Comment by dharmab** [comment]
Hi, please reference the examples in _MULTI-SERVICE 
TACTICS, TECHNIQUES, AND PROCEDURES FOR Air Control Communication_ (ATP 3-52.4), Chapter IV, Sections 9 through 17. I counted at least 19 examples of PICTURE calls which do _not_ include the "PICTURE" prefix and zero which did.
