### ISSUE TITLE
voice-playback-speed is inverse - voice-playback-pause seems to have no effect

### ISSUE THREAD

**Issue by hbjonsson** [dharmab/skyeye#379]
Not sure if documentation or implementation bug, but voice-playback-speed in the config.yaml has a comment that values above 1.0 will increase the speed which is inverse of what happends. In order to speed up the comm, i set the value to 0.8 to get closre to what we wanted :-)

adjusting the voice-playback-pause seemed to have no effect.

**Comment by dharmab** [comment]
Thanks for the report, I'll verify this when I have a moment 👍🏼

**Comment by dharmab** [comment]
Opened a PR to fix the config file. (Code was correctly documented in `--help`, just backwards in the example config file.

voice-playback-pause only changes the pause between sentences _within_ a transmission. It doesn't effect the pause _between_ transmissions, which is dynamic based on other people talking on the GCI channels.
