### ISSUE TITLE
Issue trying to install on windows machine.

### ISSUE THREAD

**Issue by TheTurbs** [dharmab/skyeye#413]
I am trying to install this wonderful application, however I'm getting the following error when I run the winsw.exe install command:

C:\Users\admin\DCSSkyeye>winsw.exe install skyeye-service.yaml
2024-12-03 13:01:35,663 FATAL - Unhandled exception
System.IO.FileNotFoundException: Unable to locate winsw.[xml|yml] file within executable directory
   at WinSW.Program.LoadConfigAndInitLoggers(Boolean inConsoleMode)
   at WinSW.Program.Run(String[] argsArray, IServiceConfig config)
   at WinSW.Program.Main(String[] args)

C:\Users\admin\DCSSkyeye>

**Comment by dharmab** [comment]
Derp, I made a mistake!

According to https://github.com/winsw/winsw/blob/master/doc/installation.md, the file `winsw.exe` should have been named `skyeye-service.exe` to match the service YAML file name.

Try renaming `winsw.exe` to `skyeye-service.exe`. If that works I can fix it in an upcoming patch release.

**Comment by TheTurbs** [comment]
Hi @dharmab,
I was able to get it installed, however I had to also change the skyeye-service.yaml file over to skyeye-service.yml  to make it work.

**Comment by TheTurbs** [comment]
Also, do you have a discord for discussing topics of skyeye?  Want to make sure this is something I can safely run on my box for my group.  we unfotunately don't have multiple boxes to run both DCS and skyeye

**Comment by dharmab** [comment]
> Also, do you have a discord for discussing topics of skyeye?

No. I do not have the time, energy or desire to moderate a public Discord server. I often hang out in the Hoggit, Lima Kilo and Digital Controllers Discord servers under the name `Halo 1 | Zaid` which is how people are usually asking ad-hoc SkyEye questions.

> Want to make sure this is something I can safely run on my box for my group. we unfotunately don't have multiple boxes to run both DCS and skyeye

As noted in the admin guide I cannot provide any guarantees around performance when running both SkyEye and DCS on the same machine; you can try, but do not be surprised if the bot takes a very long time to respond, or fails to respond in all cases.

If you are able to purchase cloud services, running the bot on Hetzner or Vultr is fairly inexpensive; one private squadron uses skyeye-scaler to automatically spin SkyEye up and down on Vultr during their weekly mission nights. Their bill is something like 3 USD per month.
