### ISSUE TITLE
Remote addresses specified in config don't seem to be respected.

### ISSUE THREAD

**Issue by Biggus22** [dharmab/skyeye#417]
**Describe the bug**
I'm likely doing something very wrong, but I've configured the address of my SRS and Tacview servers in the config file and when I inspect the error log, I can see that Skyeye is trying to connect to localhost instead of the IP I've specified.

**Steps to Reproduce**
Configure IP address for Tacview and SRS in config.yaml, start Skyeye and inspect log.  If I create an SRS server on the same machine as Skyeye is running on, it will connect to SRS fine because localhost, but will then fail to connect to Tacview on the machine that it is installed on.

**Logs**
If you have the SkyEye logs, attach them to your bug report.
[skyeye-service.err.log](https://github.com/user-attachments/files/18016717/skyeye-service.err.log)
Also attaching a zipped config file.
[config.zip](https://github.com/user-attachments/files/18016762/config.zip)

If you have a TacView ACMI recording, attach it as well.

**Platform Info**

**What does `./skyeye.exe --version` / `./skyeye --version` output?**
v0.13.2

**What OS are you running SkyEye on?**
Windows 10

**What CPU does the hardware have? How much RAM?**
Very old i7 laptop, 8GB.

**Are you running any other software besides SkyEye on this machine?**
Only SRS server for testing.  Otherwise it's just an old thing waiting to become landfill.

**Comment by dharmab** [comment]
Hi, how are you running SkyEye? Using WinSW or directly?

Looks like the config file isn't being loaded by SkyEye and it's using default values.

**Comment by Biggus22** [comment]
> Hi, how are you running SkyEye? Using WinSW (the `install` and `start` commands in the admin guide) or running `skyeye.exe` directly?
> 
> Looks like the config file isn't being loaded by SkyEye and it's using default values.
Following on from [this](https://github.com/dharmab/skyeye/issues/413) issue, I've renamed WinSW to Skyeye-service.exe and I've installed it and ran it via powershell.

**Comment by dharmab** [comment]
Reproduced the issue, root cause is misconfiguration in WinSW service files.

**Comment by dharmab** [comment]
I've released v0.13.4 which should address this problem - sorry for the inconvenience!

Please note that the commands to install and run SkyEye using WinSW have changed, so review https://github.com/dharmab/skyeye/blob/v0.13.4/docs/ADMIN.md#windows carefully for the new commands.

**Comment by Biggus22** [comment]
No need to apologise, I'm extremely grateful that you've taken on this project and you're doing awesome stuff!  Thanks for sorting it all out so quickly!
