### ISSUE TITLE
Windows Installer does not work

### ISSUE THREAD

**Issue by Real-Col-Sanders** [dharmab/skyeye#465]
Trying to install the windows version, clicking the skyeye-service.exe does nothing.

**Comment by dharmab** [comment]
See https://github.com/dharmab/skyeye/blob/main/docs/ADMIN.md#windows - `skyeye-service.exe` is a command line application and needs to be run through a command line such as PowerShell or Windows Terminal.

**Comment by Real-Col-Sanders** [comment]
Ahh yes I am dumb. Thank you, got it working now.
